services:
  my-fastapi-app:
    build:
      context: .
    image: hsris/fastapi-app
    container_name: fastapi_cont
    ports:
      - "5000:5000"
    networks:
      - kong-net

networks:
  kong-net:
    external: true
